name: sprint
version: 1.0.3+2

description: >-
  A tiny, simple-to-use and fully documented library for printing messages to
  the web console or to the terminal in a variety of modes.

homepage: https://github.com/wordcollector/sprint
repository: https://github.com/wordcollector/sprint
issue_tracker: https://github.com/wordcollector/sprint/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1

dev_dependencies:
  words: ^0.0.2+1
